### PR TITLE
Fix: check if a plugin given as a requirement is a single-specification table

### LINKED ISSUE #1038: plugin with opt option install start dir
- `nvim --version`: latest
- `git --version`: latest
- Operating system/version: macos
- Terminal name/version: kitty

### Steps to reproduce

```lua
use({
  'kristijanhusak/vim-dadbod-ui',
  cmd = { 'DBUIToggle', 'DBUIAddConnection', 'DBUI', 'DBUIFindBuffer', 'DBUIRenameBuffer' },
  config = conf.vim_dadbod_ui,
  requires = {'tpope/vim-dadbod', opt = true },
})

```

### Actual behaviour

`vim_dadobd` installed in start_dir

### Expected behaviour

install in opt_dir

### PR DESCRIPTION
**Pull request by wbthomason**
Should fix #1038 by adding a missing check for a possible `requires` case.

@glepnir, does this work for you?

### CODE REVIEW

File: lua/packer.lua [hunk 1]
```diff
@@ -267,7 +267,11 @@ manage = function(plugin_data)
   plugins[plugin_spec.short_name].url = util.remove_ending_git_url(plugin_spec.url)
 
   if plugin_spec.requires and config.ensure_dependencies then
-    if type(plugin_spec.requires) == 'string' then
+    -- Handle single plugins given as strings or single plugin specs given as tables
+    if
+      type(plugin_spec.requires) == 'string'
+      or (type(plugin_spec.requires) == 'table' and #plugin_spec.requires == 1)
```
Comment (akinsho) [inline lua/packer.lua:273]: @wbthomason how would this behave if `requires` is `requires = {{'name/thing', config = blah}}`, seems like it would wrap the plugin in another list?. Should it be if 
```suggestion
      or (type(plugin_spec.requires) == 'table' and not vim.tbl_islist(plugin_spec.requires) and #plugin_spec.requires == 1)
```

Comment (wbthomason) [reply lua/packer.lua:273]: You're right, that would be better. Thanks!

**Comment by wbthomason** [comment]
@glepnir please let us know if this does not fix your problem, but I'm going to go ahead and merge as this is a simple enough change.
